import requests
url = 'http://localhost:9000'
ledgername="Gensys"
data="<ENVELOPE><HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>Vouchers</ID>"
data+="</HEADER><BODY><DESC><STATICVARIABLES><IMPORTDUPS>@@DUPCOMBINE</IMPORTDUPS></STATICVARIABLES></DESC><DATA>"
data+="<TALLYMESSAGE><VOUCHER><DATE>20210704</DATE><NARRATION>Paid</NARRATION><PARTYLEDGERNAME>"+ledgername+"</PARTYLEDGERNAME><VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>"
data+="<PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW><VOUCHERNUMBER>1</VOUCHERNUMBER><ALLLEDGERENTRIES.LIST><LEDGERNAME>"+ledgername+"</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>"
data+="<AMOUNT>-100</AMOUNT><BILLALLOCATIONS.LIST>"
data+="<NAME>15</NAME><BILLTYPE>Agst Ref</BILLTYPE><TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE><AMOUNT>170</AMOUNT>"
data+="<INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><STBILLCATEGORIES.LIST></STBILLCATEGORIES.LIST>"
data+="</BILLALLOCATIONS.LIST></ALLLEDGERENTRIES.LIST><ALLLEDGERENTRIES.LIST><LEDGERNAME>Cash</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>"
data+="<AMOUNT>100</AMOUNT></ALLLEDGERENTRIES.LIST></VOUCHER></TALLYMESSAGE></DATA></BODY></ENVELOPE>"

req = requests.post(url=url, data=data)
print(req.text)